### ISSUE TITLE
Use with wdio-sauce-service

### ISSUE THREAD

**Issue by kyleect** [webdriverio/wdio-devtools-service#7]
I'm attempting to use `wdio-devtools-service` with `wdio-sauce-service` together but getting the following errors: 

```bash
Couldn't find Chrome process
TypeError: Cannot read property 'cmd' of undefined
    at DevToolsService._callee2$ (C:\Users\kt22954\dev\ppa-app\node_modules\wdio-devtools-service\build\devtools.js:153:81)
    at tryCatch (C:\Users\kt22954\dev\ppa-app\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\kt22954\dev\ppa-app\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\kt22954\dev\ppa-app\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\kt22954\dev\ppa-app\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\kt22954\dev\ppa-app\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

---

I wasn't able to locate `Couldn't find Chrome process` error in the `wdio-devtools-service` lib source but it does appear in the post babel-ed version.

I do have other test suites that use each service separately but can't get them to work together. Any insights on how to fix?

**Comment by christian-bromann** [comment]
@kyleect you unfortunately can't use this with Sauce Labs because wdio can't connect via WebSockets to the browser directly. However SauceLabs provides its own extended debugging features: https://www.youtube.com/watch?v=pkWv-JIf4eo
