### ISSUE TITLE
version 0.1.2 - Using browser.cdp() in WebdriverIO before hook causes "TypeError: browser.cdp is not a function"

### ISSUE THREAD

**Issue by mansn** [webdriverio/wdio-devtools-service#8]
Using browser.cdp() in the wdio.conf.js **before hook** causes "TypeError: browser.cdp is not a function". This issue started in wdio-devtools-service 0.1.2, but disappears if I downgrade to version 0.1.1.

wdio.conf.js:
```
before: function (capabilities, specs) {
  browser.cdp('Page', 'enable');
  browser.on('Page.frameResized', function() {
    console.log('frameResized event was raised!');
  });
},
```

When running any test:
```
TypeError: browser.cdp is not a function
    at Object.before (C:\gitworkspace\UMBAutotest\confs\wdio.conf.js:285:21)
    at execHook (C:\gitworkspace\UMBAutotest\node_modules\wdio-sync\build\index.js:162:35)
```
The error doesn't occur if it to e.g. the **beforeTest hook**.

Note: I'm also using the wdio-chromedriver-service.
Chromedriver 2.36.540470
**chrome://version**
```
Google Chrome | 65.0.3325.146 (Official Build) (64-bit) (cohort: 65_win_146)
-- | --
Revision | f926414266f7aecb5ec1bf1b5f93f8716976ceef-refs/branch-heads/3325@{#669}
OS | Windows
JavaScript | V8 6.5.254.31
Flash | 24.0.0.189 internal-not-yet-present
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-extensions --disable-extensions-except="C:\Users\9037\AppData\Local\Temp\scoped_dir11524_11925\internal" --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --ignore-certificate-errors --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12347 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\9037\AppData\Local\Temp\scoped_dir11524_8190" --flag-switches-begin --flag-switches-end data:,
Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path | C:\Users\9037\AppData\Local\Temp\scoped_dir11524_8190\Default
Compiler | clang
```

**Comment by christian-bromann** [comment]
Hey @mansn ,
the service adds the cdp command in the before hook and since all hooks are executed at the same time it won't be registered at when you use it in the before hook. You can workaround that by doing:

```js
before: function () {
    return new Promise(function(resolve) {
        process.nextTick(function() {
            browser.cdp('Page', 'enable');
            browser.on('Page.frameResized', function() {
                console.log('frameResized event was raised!');
            })
        })
    })
},
```

**Comment by mansn** [comment]
@christian-bromann Thanks for the suggested solution. That didn't work for me though. Does that work for you? I guess your code example is missing where to resolve the promise? I'm sorry if I'm missing something here. I tried resolving the promise at various points, but with no luck.

I'm running:
webdriverio@4.10.2
wdio-devtools-service@0.1.2
wdio-chromedriver-service@0.1.2
Chromedriver 2.36.540470
Google Chrome | 65.0.3325.146 (Official Build) (64-bit) (cohort: 65_win_146)

**Comment by christian-bromann** [comment]
You right, it should be:
```js
before: function () {
    return new Promise(function(resolve) {
        process.nextTick(function() {
            browser.cdp('Page', 'enable');
            browser.on('Page.frameResized', function() {
                console.log('frameResized event was raised!');
            })
            resolve()
        })
    })
},
```
