### ISSUE TITLE
Fail to load, as Babel is missing (or incompatible version is installed)

### ISSUE THREAD

**Issue by glukki** [webdriverio/wdio-devtools-service#9]
As Babel is mentioned only in the `devDependencies`, Babel may not be installed at all (or incompatible version may be installed by other module).
The `build/devtools.js` file requires `babel-runtime/helpers/asyncToGenerator` file and may end up with this error:
```
ERROR: Couldn't initialise service "devtools".
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/wdio-devtools-service/build/devtools.js:15:26)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

Some of my other dependencies made Babel v5 available, and in that version this file has different name: `babel-runtime/helpers/async-to-generator.js`.

Listing Babel in `dependencies` would fix this issue.

**Comment by christian-bromann** [comment]
Fixed with 0.1.3
